SELECT NM_ESTADO, NM_CIDADE 
FROM DB_ESTADO
LEFT JOIN DB_CIDADE ON DB_ESTADO.SG_ESTADO = DB_CIDADE.SG_ESTADO
ORDER BY NM_ESTADO, NM_CIDADE ASC;



--Puxar codigo produto, descrição do produto, valor do produto, sub-categoria e categoria
WITH PRODUTOS_CATEG AS(
    SELECT 
        DB_PRODUTO.CD_PRODUTO,
        DB_PRODUTO.DS_PRODUTO,
        DB_PRODUTO.VL_UNITARIO, 
        DB_SUB_CATEGORIA_PROD.DS_SUB_CATEGORIA_PROD, 
        DB_CATEGORIA_PROD.DS_CATEGORIA_PROD
    FROM DB_PRODUTO
    INNER JOIN DB_SUB_CATEGORIA_PROD 
        ON DB_PRODUTO.CD_SUB_CATEGORIA_PROD = DB_SUB_CATEGORIA_PROD.CD_SUB_CATEGORIA_PROD
    INNER JOIN DB_CATEGORIA_PROD
        ON DB_SUB_CATEGORIA_PROD.CD_CATEGORIA_PROD = DB_CATEGORIA_PROD.CD_CATEGORIA_PROD    
    ORDER BY DB_PRODUTO.CD_PRODUTO, DB_PRODUTO.VL_UNITARIO DESC
    --ORDER BY DB_PRODUTO.VL_UNITARIO, DB_PRODUTO.CD_PRODUTO DESC
)

SELECT * FROM PRODUTOS_CATEG
WHERE DS_SUB_CATEGORIA_PROD = 'Doce'

   